name = "PigmentColorMixing"
uuid = "cbc7f502-98d2-48bf-90bf-0bf6c18576e9"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>", "Adrian Hill <adrian.hill@mailbox.org>", "and contributors"]
version = "0.0.1-DEV"

[compat]
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
